# Generated by Django 4.2.2 on 2023-06-28 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_myuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('address_link', models.TextField(blank=True, max_length=250, null=True)),
                ('phonenumber', models.CharField(max_length=12, unique=True)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='images/')),
                ('clinic_start_time', models.IntegerField(default=9, null=True)),
                ('clinic_end_time', models.IntegerField(default=19, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
