# Generated by Django 4.2.2 on 2023-06-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='qualification',
            field=models.CharField(blank=True, default='Not Specified', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='type',
            field=models.TextField(blank=True, default='Others', max_length=250, null=True),
        ),
    ]
