# Generated by Django 4.2.2 on 2023-06-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_session_doctor_id_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(blank=True, default='Comman Disease', max_length=200),
        ),
    ]
