# Generated by Django 4.2.2 on 2023-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_session_session_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vist',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.CharField(blank=True, max_length=250, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('sugar', models.IntegerField(blank=True, null=True)),
                ('bp', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
