# Generated by Django 4.2.2 on 2023-06-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vist'),
    ]

    operations = [
        migrations.AddField(
            model_name='vist',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='main.session'),
        ),
    ]
