# Generated by Django 4.2.2 on 2023-06-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vist_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField(blank=True, max_length=250, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('sugar', models.IntegerField(blank=True, null=True)),
                ('bp', models.CharField(blank=True, max_length=10, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='main.session')),
            ],
        ),
        migrations.DeleteModel(
            name='Vist',
        ),
    ]
