# Generated by Django 4.2.2 on 2023-07-01 03:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_visit_delete_vist'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='url_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
