# Generated by Django 4.2.2 on 2023-07-01 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_visit_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='url_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
