# Generated by Django 4.2.2 on 2023-07-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_visit_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
