# Generated by Django 4.2.2 on 2023-07-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_visit_sugar_alter_visit_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
