# Generated by Django 4.2.2 on 2023-06-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_visit_delete_vist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('morning', models.IntegerField(blank=True, default=0, null=True)),
                ('afternoon', models.IntegerField(blank=True, default=0, null=True)),
                ('night', models.IntegerField(blank=True, default=0, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='prescription.medicine')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='main.visit')),
            ],
        ),
    ]
