# Generated by Django 4.2.2 on 2023-06-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_medicine_med_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='num_days',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
